name: Bug Report
description: Report a bug in LOOM
title: "[Bug]: "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the information below.
  
  - type: dropdown
    id: backend
    attributes:
      label: Backend
      description: Which backend were you using?
      options:
        - Python (pure)
        - Numba
        - Not sure
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: LOOM Version
      description: What version of LOOM?
      placeholder: "1.1.0"
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of the bug
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Steps to reproduce the behavior
      placeholder: |
        1. Import loom
        2. Set backend to 'numba'
        3. Run loom.matmul(A, B)
        4. See error
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true
  
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: System information
      placeholder: |
        - OS: Ubuntu 22.04
        - Python: 3.11.5
        - Numba: 0.58.1 (if applicable)
    validations:
      required: true
